### ISSUE TITLE
rename to dascombat_shiny_operator

### ISSUE THREAD

**Issue by wptmdoorn** [tercen/dascombat_shiny_fit_operator#3]
since the shiny operator now does fitting and prediction I would propose to rename it to `dascombat_shiny_operator`. 
we then have three DASCOMBAT operators in our operator's catalog:

- **dascombat_fit_operator:** this performs fitting without an interface
- **dascombat_prediction_operator:** this performs prediction without an interface (using the model from `dascombat_fit_operator`)
- **dascombat_shiny_operator:** this performs fitting AND prediction, alone or in subsequent data steps, including an interface that plots the data

**Comment by wptmdoorn** [comment]
if approved by @ginberg or @fnaji will rename

**Comment by fnaji** [comment]
This makes sense, please go ahead

**Comment by ginberg** [comment]
yes that makes sense
